version: '2'
services:
  backend:
    container_name: jwtservice_backend
    image: jwt-python:latest
    volumes:
      - ./app/:/app
      - ./logs/ngix/:/var/log/nginx
      - ./logs/gunicorn/:/var/log/gunicorn
    ports:
      - 9001:80
